version: '3'

volumes:
  ikev2-vpn-data:

services:
  vpn:
    build:
      context: .
    restart: always
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    hostname: pd-ipsec-vpn-server
    container_name: pd-ipsec-vpn-server
    volumes:
      - ikev2-vpn-data:/etc/ipsec.d
      - /lib/modules:/lib/modules:ro
      - /bases/.system/ikev2-vpn/ipsec.secrets:/etc/ipsec.secrets
      - /bases/.system/ikev2-vpn/plandoc.conf:/etc/ipsec.d/plandoc.conf
      - /bases/.system/ikev2-vpn/entrypoint.sh:/etc/ipsec/entrypoint.sh
    entrypoint: ["/etc/ipsec/entrypoint.sh"]